[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cloelike"
version = "0.2"
description = "Likelihood module for Euclid primary observables for the CLOE project"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "M. Bonici", email = "marco.bonici@uwaterloo.ca" },
    { name = "G. Cañas-Herrera", email = "guadalupe.canasherrera@esa.int" },
    { name = "P. Carrilho", email = "pedro.carrilho@ed.ac.uk" },
    { name = "S. Casas", email = "casas@physik.rwth-aachen.de" },
    { name = "C. Moretti", email = "cmoretti@sissa.it" },
    { name = "A. Pezzotta", email = "andrea.pezzotta@inaf.it" }
]

requires-python = ">=3.10,<3.11"
