[tool.poetry]
name = "cloelike"
version = "0.1"
description = "Likelihood module for Euclid primary observables for the CLOE project"
authors = [
    "M. Bonici <marco.bonici@uwaterloo.ca>",
    "G. Cañas-Herrera <guadalupe.canasherrera@esa.int>",
    "P. Carrilho <pedro.carrilho@ed.ac.uk>",
    "S. Casas <casas@physik.rwth-aachen.de>",
    "C. Moretti <cmoretti@sissa.it>",
    "A. Pezzotta <andrea.pezzotta@inaf.it>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "<2.0"
requests = "^2.32.3"
euclidlib = "v2025.2"

# core cloelib functionality
cloelib = { git = "https://github.com/cloe-org/cloelib.git" }

# explicitly install extras
camb = "*"
comet-emu = "*"
HMcode2020Emu = { git = "https://github.com/MariaTsedrik/HMcode2020Emu.git" }

[tool.poetry.group.test.dependencies]
pytest = "^8.3"
