blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/cloe-org/cloelike/discussions
    about: Ask general questions or get help with cloelike in the Discussions section
